reworked rofi theme using HyprNova to make it a gnome-like menu

diff --git a/.local/bin/set-wallpaper b/.local/bin/set-wallpaper
--- a/.local/bin/set-wallpaper
+++ b/.local/bin/set-wallpaper
@@ -2,12 +2,18 @@
 
 # check file existence
 if [ ! -f $1 ]; then
-  echo "File $1 not found!"
-  exit 1
+	echo "File $1 not found!"
+	exit 1
 fi
 
+# check cache folder existence
+if [ ! -d ~/.cache/wal ]; then
+	mkdir ~/.cache/wal
+fi
+
+
 # set passed wallpaper as current wallpaper
-ln -s -r -f $1 ~/.cache/hyprland/current-wallpaper
+ln -s -r -f $1 ~/.cache/wal/current-wallpaper
 ln -s -r -f $1 ~/.mozilla/firefox/nyanmaths/chrome/ASSETS/wallpaper/wallpaper
 
 
